#!/bin/bash
# =============================================================================
# Script   : ssl_prepare_cert.sh
# Purpose  : Prepare an SSL certificate for Nginx deployment.
#            Three modes:
#              SELF    – self-signed certificate (testing / smoke test)
#              EASYRSA – internal CA via Easy-RSA (internal/lab environments)
#              REQUEST – generate private key + CSR for submission to a CA
#
#            All parameters (CN, SAN, key size, output paths …) are read from
#            08-SSL/ssl.conf, shown as defaults in interactive prompts, and
#            written back after confirmation so the next run uses them again.
#
#            Does NOT deploy to Nginx – run 09-Install/03-root_nginx_ssl.sh
#            --apply afterwards.
#
# Call     : ./08-SSL/ssl_prepare_cert.sh SELF    [--apply]
#            ./08-SSL/ssl_prepare_cert.sh EASYRSA  [--apply]
#            ./08-SSL/ssl_prepare_cert.sh REQUEST  [--apply]
#
#            Without --apply : show plan / parameters, no files written
#            With    --apply : generate key / cert / CSR
#
# Requires : openssl (all modes)
#            easy-rsa package (EASYRSA mode)
# Author   : Gunther Pipperr | https://pipperr.de
# License  : Apache 2.0
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
LIB_SH="$ROOT_DIR/00-Setup/IHateWeblogic_lib.sh"

# --- Source library -----------------------------------------------------------
if [ ! -f "$LIB_SH" ]; then
    printf "\033[31mFATAL\033[0m: Library not found: %s\n" "$LIB_SH" >&2
    exit 2
fi
# shellcheck source=../00-Setup/IHateWeblogic_lib.sh
source "$LIB_SH"

# --- Source environment.conf --------------------------------------------------
check_env_conf "$ROOT_DIR/environment.conf" || exit 2
# shellcheck source=../environment.conf
source "$ROOT_DIR/environment.conf"

# =============================================================================
# ssl.conf handling
# =============================================================================
SSL_CONF="$SCRIPT_DIR/ssl.conf"
SSL_CONF_TEMPLATE="$SCRIPT_DIR/ssl.conf.template"

# Variable defaults (overridden by ssl.conf / ssl.conf.template when present)
SSL_CN="${WLS_SERVER_FQDN:-$(hostname -f 2>/dev/null || hostname)}"
SSL_SAN="DNS:${SSL_CN}"
SSL_COUNTRY="DE"
SSL_STATE="Bavaria"
SSL_CITY="Munich"
SSL_ORG="Company"
SSL_ORG_UNIT=""
SSL_EMAIL=""
SSL_KEY_ALGO="RSA"
SSL_KEY_SIZE="4096"
SSL_EC_CURVE="secp384r1"
SSL_DAYS="825"
SSL_CERT_FILE="$SCRIPT_DIR/certs/server.crt"
SSL_KEY_FILE="$SCRIPT_DIR/certs/server.key"
SSL_CHAIN_FILE="$SCRIPT_DIR/certs/chain.crt"
SSL_CSR_FILE="$SCRIPT_DIR/certs/server.csr"
EASYRSA_PKI_DIR="/srv/gpi_ca"
EASYRSA_CA_DAYS="3650"
SSL_LAST_MODE="SELF"

_load_ssl_conf() {
    if [ -f "$SSL_CONF" ]; then
        # shellcheck source=ssl.conf
        source "$SSL_CONF"
        return 0
    elif [ -f "$SSL_CONF_TEMPLATE" ]; then
        source "$SSL_CONF_TEMPLATE"
        # Use WLS_SERVER_FQDN from environment.conf as initial CN
        SSL_CN="${WLS_SERVER_FQDN:-$SSL_CN}"
        SSL_SAN="DNS:${SSL_CN}"
        return 1
    fi
    return 1
}

_save_ssl_conf() {
    {
        printf "# ssl.conf – SSL Certificate Configuration\n"
        printf "# Generated by ssl_prepare_cert.sh – %s\n" "$(date '+%Y-%m-%d %H:%M:%S')"
        printf "# Edit directly or re-run ssl_prepare_cert.sh to update.\n\n"
        printf "SSL_CN=\"%s\"\n"            "$SSL_CN"
        printf "SSL_SAN=\"%s\"\n"           "$SSL_SAN"
        printf "SSL_COUNTRY=\"%s\"\n"       "$SSL_COUNTRY"
        printf "SSL_STATE=\"%s\"\n"         "$SSL_STATE"
        printf "SSL_CITY=\"%s\"\n"          "$SSL_CITY"
        printf "SSL_ORG=\"%s\"\n"           "$SSL_ORG"
        printf "SSL_ORG_UNIT=\"%s\"\n"      "$SSL_ORG_UNIT"
        printf "SSL_EMAIL=\"%s\"\n\n"       "$SSL_EMAIL"
        printf "SSL_KEY_ALGO=\"%s\"\n"      "$SSL_KEY_ALGO"
        printf "SSL_KEY_SIZE=\"%s\"\n"      "$SSL_KEY_SIZE"
        printf "SSL_EC_CURVE=\"%s\"\n"      "$SSL_EC_CURVE"
        printf "SSL_DAYS=\"%s\"\n\n"        "$SSL_DAYS"
        printf "SSL_CERT_FILE=\"%s\"\n"     "$SSL_CERT_FILE"
        printf "SSL_KEY_FILE=\"%s\"\n"      "$SSL_KEY_FILE"
        printf "SSL_CHAIN_FILE=\"%s\"\n"    "$SSL_CHAIN_FILE"
        printf "SSL_CSR_FILE=\"%s\"\n\n"    "$SSL_CSR_FILE"
        printf "EASYRSA_PKI_DIR=\"%s\"\n"   "$EASYRSA_PKI_DIR"
        printf "EASYRSA_CA_DAYS=\"%s\"\n\n" "$EASYRSA_CA_DAYS"
        printf "SSL_LAST_MODE=\"%s\"\n"     "$MODE"
    } > "$SSL_CONF"
    chmod 600 "$SSL_CONF"
}

# =============================================================================
# Arguments
# =============================================================================
MODE=""
APPLY=false

_usage() {
    printf "Usage: %s MODE [--apply]\n\n" "$(basename "$0")"
    printf "  %-10s %s\n" "SELF"     "Generate self-signed certificate (testing only)"
    printf "  %-10s %s\n" "EASYRSA"  "Issue certificate from internal Easy-RSA CA"
    printf "  %-10s %s\n" "REQUEST"  "Generate private key + CSR for external CA"
    printf "\n  %-10s %s\n" "--apply" "Write output files (default: dry-run)"
    printf "\nParameters are read from 08-SSL/ssl.conf (created on first run).\n"
    exit 0
}

for _arg in "$@"; do
    case "${_arg^^}" in
        SELF|EASYRSA|REQUEST) MODE="${_arg^^}" ;;
        --APPLY)  APPLY=true ;;
        --HELP|-H) _usage ;;
        *) warn "Unknown argument: $_arg" ;;
    esac
done
unset _arg

if [ -z "$MODE" ]; then
    _load_ssl_conf 2>/dev/null || true
    printf "\033[31mERROR\033[0m: No mode specified.\n" >&2
    printf "  Usage: %s SELF|EASYRSA|REQUEST [--apply]\n" "$(basename "$0")" >&2
    printf "  Last used mode: %s\n" "${SSL_LAST_MODE:-SELF}" >&2
    exit 1
fi

# --- Log setup ----------------------------------------------------------------
LOG_FILE="$ROOT_DIR/log/$(date +%Y%m%d)/ssl_prepare_${MODE,,}_$(date +%H%M%S).log"
mkdir -p "$(dirname "$LOG_FILE")"
{
    printf "# ssl_prepare_cert.sh log\n"
    printf "# Mode    : %s\n" "$MODE"
    printf "# Started : %s\n" "$(date '+%Y-%m-%d %H:%M:%S')"
    printf "# Host    : %s\n" "$(_get_hostname)"
    printf "# Apply   : %s\n" "$APPLY"
} > "$LOG_FILE"

# =============================================================================
# Header
# =============================================================================
printLine
printf "\n\033[1m  IHateWeblogic – SSL Certificate Preparation (%s)\033[0m\n" "$MODE" \
    | tee -a "$LOG_FILE"
printf "  Host  : %s\n" "$(_get_hostname)" | tee -a "$LOG_FILE"
printf "  Mode  : %s\n" "$MODE"            | tee -a "$LOG_FILE"
printf "  Apply : %s\n" "$APPLY"           | tee -a "$LOG_FILE"
printf "  Log   : %s\n" "$LOG_FILE"        | tee -a "$LOG_FILE"
printLine

# =============================================================================
# Load ssl.conf
# =============================================================================
section "Loading SSL configuration"

if _load_ssl_conf; then
    ok "Settings loaded: $SSL_CONF"
else
    info "ssl.conf not found – using defaults (saved after confirmation)"
fi

# =============================================================================
# Interactive parameter prompts
# =============================================================================
section "Certificate Parameters"
info "Review settings – press Enter to accept the current value."
printf "\n"

# nameref-based prompt (bash 4.3+ / OL9)
_prompt() {
    local label="$1"
    local -n _pvar="$2"
    local _cur="${_pvar:-}"
    local _input
    printf "  %-24s [\033[36m%s\033[0m]: " "$label" "$_cur" >&2
    read -r _input
    _pvar="${_input:-$_cur}"
}

_prompt "Common Name (FQDN)"      SSL_CN
_prompt "Alt Names (space-sep)"   SSL_SAN
_prompt "Country (2 letters)"     SSL_COUNTRY
_prompt "State / Province"        SSL_STATE
_prompt "City"                    SSL_CITY
_prompt "Organization"            SSL_ORG
_prompt "Org Unit (empty=skip)"   SSL_ORG_UNIT
_prompt "Key algorithm (RSA/EC)"  SSL_KEY_ALGO
SSL_KEY_ALGO="${SSL_KEY_ALGO^^}"
if [ "$SSL_KEY_ALGO" = "RSA" ]; then
    _prompt "RSA key size (2048/4096)" SSL_KEY_SIZE
else
    _prompt "EC curve"                 SSL_EC_CURVE
    SSL_KEY_ALGO="EC"
fi
_prompt "Validity (days)"         SSL_DAYS
_prompt "Certificate output path" SSL_CERT_FILE
_prompt "Private key output path" SSL_KEY_FILE
if [ "$MODE" = "EASYRSA" ]; then
    _prompt "CA chain output path"    SSL_CHAIN_FILE
    _prompt "Easy-RSA PKI directory"  EASYRSA_PKI_DIR
    _prompt "CA validity (days)"      EASYRSA_CA_DAYS
fi
if [ "$MODE" = "REQUEST" ]; then
    _prompt "CSR output path"         SSL_CSR_FILE
fi

# Ensure CN is always the first SAN entry
if ! printf '%s' "$SSL_SAN" | grep -qw "DNS:$SSL_CN"; then
    SSL_SAN="DNS:${SSL_CN}${SSL_SAN:+ $SSL_SAN}"
    info "CN added to SAN: $SSL_SAN"
fi

printf "\n"

# =============================================================================
# Summary of confirmed parameters
# =============================================================================
section "Confirmed Parameters"

printList "Mode"         22 "$MODE"                                         | tee -a "$LOG_FILE"
printList "CN"           22 "$SSL_CN"                                       | tee -a "$LOG_FILE"
printList "SAN"          22 "$SSL_SAN"                                      | tee -a "$LOG_FILE"
printList "Subject"      22 "C=$SSL_COUNTRY, ST=$SSL_STATE, L=$SSL_CITY"   | tee -a "$LOG_FILE"
printList "Org"          22 "$SSL_ORG${SSL_ORG_UNIT:+, OU=$SSL_ORG_UNIT}"  | tee -a "$LOG_FILE"
printList "Key"          22 "${SSL_KEY_ALGO} / ${SSL_KEY_SIZE:-$SSL_EC_CURVE}" \
                                                                             | tee -a "$LOG_FILE"
printList "Validity"     22 "${SSL_DAYS} days"                              | tee -a "$LOG_FILE"
printList "Cert file"    22 "$SSL_CERT_FILE"                                | tee -a "$LOG_FILE"
printList "Key file"     22 "$SSL_KEY_FILE"                                 | tee -a "$LOG_FILE"
[ "$MODE" = "EASYRSA" ] && printList "Chain file"  22 "$SSL_CHAIN_FILE"    | tee -a "$LOG_FILE"
[ "$MODE" = "EASYRSA" ] && printList "EASYRSA PKI" 22 "$EASYRSA_PKI_DIR"   | tee -a "$LOG_FILE"
[ "$MODE" = "REQUEST" ] && printList "CSR file"    22 "$SSL_CSR_FILE"      | tee -a "$LOG_FILE"

# Always save parameters (even in dry-run)
_save_ssl_conf

if ! $APPLY; then
    printf "\n"
    warn "Dry-run – no certificate files written. Use --apply to generate."
    ok "Parameters saved: $SSL_CONF"
    print_summary; exit "$EXIT_CODE"
fi

ok "Parameters saved: $SSL_CONF"

# =============================================================================
# Helper: build openssl.cnf
# =============================================================================
_build_openssl_cnf() {
    local cnf_file="$1"
    local ext_section="$2"   # x509_extensions (SELF) or req_extensions (REQUEST)
    local san_csv="${SSL_SAN// /,}"
    {
        printf "[req]\n"
        printf "distinguished_name = dn\n"
        printf "%s = san_ext\n" "$ext_section"
        printf "prompt = no\n\n"
        printf "[dn]\n"
        printf "C = %s\n"  "$SSL_COUNTRY"
        printf "ST = %s\n" "$SSL_STATE"
        printf "L = %s\n"  "$SSL_CITY"
        printf "O = %s\n"  "$SSL_ORG"
        [ -n "$SSL_ORG_UNIT" ] && printf "OU = %s\n" "$SSL_ORG_UNIT"
        [ -n "$SSL_EMAIL"    ] && printf "emailAddress = %s\n" "$SSL_EMAIL"
        printf "CN = %s\n\n" "$SSL_CN"
        printf "[san_ext]\n"
        printf "subjectAltName = %s\n" "$san_csv"
        printf "keyUsage = critical, keyEncipherment, digitalSignature\n"
        printf "extendedKeyUsage = serverAuth\n"
    } > "$cnf_file"
}

# =============================================================================
# Mode: SELF – self-signed certificate
# =============================================================================
_mode_self() {
    section "Generating self-signed certificate"

    local _cnf
    _cnf="$(mktemp /tmp/ssl_openssl_XXXXXX.cnf)"
    chmod 600 "$_cnf"
    _build_openssl_cnf "$_cnf" "x509_extensions"

    mkdir -p "$(dirname "$SSL_CERT_FILE")" "$(dirname "$SSL_KEY_FILE")"

    local _rc=0
    if [ "$SSL_KEY_ALGO" = "EC" ]; then
        info "Generating EC key (curve: $SSL_EC_CURVE) ..."
        openssl ecparam -name "$SSL_EC_CURVE" -genkey -noout \
            -out "$SSL_KEY_FILE" 2>&1 | tee -a "$LOG_FILE"
        _rc="${PIPESTATUS[0]}"
        if [ "$_rc" -ne 0 ]; then
            fail "EC key generation failed (rc=$_rc)"; rm -f "$_cnf"; return "$_rc"
        fi
        chmod 600 "$SSL_KEY_FILE"
        info "Signing certificate ..."
        openssl req -x509 -new -key "$SSL_KEY_FILE" \
            -out "$SSL_CERT_FILE" -days "$SSL_DAYS" \
            -config "$_cnf" 2>&1 | tee -a "$LOG_FILE"
        _rc="${PIPESTATUS[0]}"
    else
        info "Generating RSA-${SSL_KEY_SIZE} key + self-signed certificate ..."
        openssl req -x509 \
            -newkey "rsa:${SSL_KEY_SIZE}" \
            -keyout "$SSL_KEY_FILE" \
            -out    "$SSL_CERT_FILE" \
            -days   "$SSL_DAYS" \
            -nodes \
            -config "$_cnf" 2>&1 | tee -a "$LOG_FILE"
        _rc="${PIPESTATUS[0]}"
        chmod 600 "$SSL_KEY_FILE"
    fi

    rm -f "$_cnf"

    if [ "$_rc" -ne 0 ]; then
        fail "Certificate generation failed (rc=$_rc)"; return "$_rc"
    fi

    chmod 644 "$SSL_CERT_FILE"
    ok "Certificate : $SSL_CERT_FILE"
    ok "Private key : $SSL_KEY_FILE  (mode 600)"

    info "Certificate details:"
    openssl x509 -noout -subject -issuer -enddate -in "$SSL_CERT_FILE" \
        2>/dev/null | sed 's/^/  /' | tee -a "$LOG_FILE"
    openssl x509 -noout -text -in "$SSL_CERT_FILE" 2>/dev/null \
        | grep -A2 "Subject Alternative" | sed 's/^/  /' | tee -a "$LOG_FILE"

    warn "Self-signed certificate: browsers will show a security warning."
    info "  Next step: ./09-Install/03-root_nginx_ssl.sh --apply"
}

# =============================================================================
# Mode: EASYRSA – internal CA
# =============================================================================
_mode_easyrsa() {
    section "Easy-RSA internal CA"

    # Locate easyrsa binary
    local _easyrsa=""
    for _c in \
        "$EASYRSA_PKI_DIR/easy-rsa/easyrsa" \
        "/usr/share/easy-rsa/3/easyrsa" \
        "/usr/share/easy-rsa/easyrsa"; do
        [ -x "$_c" ] && { _easyrsa="$_c"; break; }
    done

    if [ -z "$_easyrsa" ]; then
        fail "easyrsa not found."
        info "  Install: dnf install oracle-epel-release-el9 && dnf install easy-rsa"
        return 1
    fi
    ok "easyrsa: $_easyrsa"

    # Create PKI root dir + easyrsa symlink if needed
    if [ ! -d "$EASYRSA_PKI_DIR" ]; then
        mkdir -p "$EASYRSA_PKI_DIR" && chmod 700 "$EASYRSA_PKI_DIR"
        [ "$_easyrsa" != "$EASYRSA_PKI_DIR/easy-rsa/easyrsa" ] && \
            ln -s "$(dirname "$_easyrsa")" "$EASYRSA_PKI_DIR/easy-rsa"
        info "PKI root created: $EASYRSA_PKI_DIR"
    fi

    local _pki="$EASYRSA_PKI_DIR/pki"

    # Init PKI
    if [ ! -d "$_pki" ]; then
        info "Initializing PKI ..."
        ( cd "$EASYRSA_PKI_DIR" && "$_easyrsa" init-pki 2>&1 ) | tee -a "$LOG_FILE"
        ok "PKI initialized: $_pki"
    else
        ok "PKI exists: $_pki"
    fi

    # Write Easy-RSA vars
    {
        printf "set_var EASYRSA_CA_EXPIRE    %s\n" "$EASYRSA_CA_DAYS"
        printf "set_var EASYRSA_CERT_EXPIRE  %s\n" "$SSL_DAYS"
        printf "set_var EASYRSA_REQ_COUNTRY  \"%s\"\n" "$SSL_COUNTRY"
        printf "set_var EASYRSA_REQ_PROVINCE \"%s\"\n" "$SSL_STATE"
        printf "set_var EASYRSA_REQ_CITY     \"%s\"\n" "$SSL_CITY"
        printf "set_var EASYRSA_REQ_ORG      \"%s\"\n" "$SSL_ORG"
        printf "set_var EASYRSA_REQ_OU       \"%s\"\n" "$SSL_ORG_UNIT"
        printf "set_var EASYRSA_REQ_EMAIL    \"%s\"\n" "$SSL_EMAIL"
        printf "set_var EASYRSA_REQ_CN       \"%s CA\"\n" "$SSL_ORG"
    } > "$_pki/vars"
    ok "Easy-RSA vars written"

    # Build CA if missing
    if [ ! -f "$_pki/ca.crt" ]; then
        info "Building CA (you will be prompted for a CA passphrase) ..."
        ( cd "$EASYRSA_PKI_DIR" && "$_easyrsa" build-ca 2>&1 ) | tee -a "$LOG_FILE"
        if [ ! -f "$_pki/ca.crt" ]; then
            fail "CA build failed – pki/ca.crt not found"; return 1
        fi
        ok "CA created: $_pki/ca.crt"
    else
        ok "CA exists: $_pki/ca.crt"
    fi

    # Issue server certificate
    local _issued="$_pki/issued/${SSL_CN}.crt"
    local _issued_key="$_pki/private/${SSL_CN}.key"

    if [ -f "$_issued" ]; then
        warn "Server cert already exists: $_issued (not re-issued)"
        info "  To re-issue: remove existing cert and run again."
    else
        info "Issuing server certificate for: $SSL_CN ..."
        ( cd "$EASYRSA_PKI_DIR" && \
            "$_easyrsa" build-server-full "$SSL_CN" nopass 2>&1 ) | tee -a "$LOG_FILE"
        if [ ! -f "$_issued" ]; then
            fail "Server cert issuance failed"; return 1
        fi
        ok "Server certificate issued"
    fi

    # Copy to staging paths
    mkdir -p "$(dirname "$SSL_CERT_FILE")" "$(dirname "$SSL_KEY_FILE")" \
             "$(dirname "$SSL_CHAIN_FILE")"
    cp "$_issued"      "$SSL_CERT_FILE"  && chmod 644 "$SSL_CERT_FILE"
    cp "$_issued_key"  "$SSL_KEY_FILE"   && chmod 600 "$SSL_KEY_FILE"
    cp "$_pki/ca.crt"  "$SSL_CHAIN_FILE" && chmod 644 "$SSL_CHAIN_FILE"

    ok "Certificate : $SSL_CERT_FILE"
    ok "Private key : $SSL_KEY_FILE  (mode 600)"
    ok "CA chain    : $SSL_CHAIN_FILE"
    info "  Distribute $SSL_CHAIN_FILE to all clients as Trusted Root CA"
    info "  Next step: ./09-Install/03-root_nginx_ssl.sh --apply"
}

# =============================================================================
# Mode: REQUEST – key + CSR for external CA
# =============================================================================
_mode_request() {
    section "Generating CSR for CA submission"

    local _cnf
    _cnf="$(mktemp /tmp/ssl_openssl_XXXXXX.cnf)"
    chmod 600 "$_cnf"
    _build_openssl_cnf "$_cnf" "req_extensions"

    mkdir -p "$(dirname "$SSL_KEY_FILE")" "$(dirname "$SSL_CSR_FILE")"

    local _rc=0
    if [ "$SSL_KEY_ALGO" = "EC" ]; then
        info "Generating EC key (curve: $SSL_EC_CURVE) ..."
        openssl ecparam -name "$SSL_EC_CURVE" -genkey -noout \
            -out "$SSL_KEY_FILE" 2>&1 | tee -a "$LOG_FILE"
        _rc="${PIPESTATUS[0]}"
        if [ "$_rc" -ne 0 ]; then
            fail "EC key generation failed"; rm -f "$_cnf"; return "$_rc"
        fi
        chmod 600 "$SSL_KEY_FILE"
        info "Generating CSR ..."
        openssl req -new -key "$SSL_KEY_FILE" \
            -out "$SSL_CSR_FILE" -config "$_cnf" 2>&1 | tee -a "$LOG_FILE"
        _rc="${PIPESTATUS[0]}"
    else
        info "Generating RSA-${SSL_KEY_SIZE} key + CSR ..."
        openssl req -new \
            -newkey "rsa:${SSL_KEY_SIZE}" \
            -keyout "$SSL_KEY_FILE" \
            -out    "$SSL_CSR_FILE" \
            -nodes \
            -config "$_cnf" 2>&1 | tee -a "$LOG_FILE"
        _rc="${PIPESTATUS[0]}"
        chmod 600 "$SSL_KEY_FILE"
    fi

    rm -f "$_cnf"
    [ "$_rc" -ne 0 ] && { fail "CSR generation failed (rc=$_rc)"; return "$_rc"; }

    ok "CSR         : $SSL_CSR_FILE"
    ok "Private key : $SSL_KEY_FILE  (mode 600)"

    info "CSR subject:"
    openssl req -noout -subject -in "$SSL_CSR_FILE" 2>/dev/null \
        | sed 's/^/  /' | tee -a "$LOG_FILE"
    info "CSR SAN:"
    openssl req -noout -text -in "$SSL_CSR_FILE" 2>/dev/null \
        | grep -A2 "Subject Alternative" | sed 's/^/  /' | tee -a "$LOG_FILE"

    printf "\n"
    info "Next steps:"
    info "  1. Send to CA : $SSL_CSR_FILE"
    info "  2. Keep secret: $SSL_KEY_FILE  (never send to CA)"
    info "  3. After receiving signed cert: update SSL_CERT_FILE in ssl.conf"
    info "  4. Deploy     : ./09-Install/03-root_nginx_ssl.sh --apply"
}

# =============================================================================
# Execute selected mode
# =============================================================================
section "Executing mode: $MODE"

case "$MODE" in
    SELF)    _mode_self    ;;
    EASYRSA) _mode_easyrsa ;;
    REQUEST) _mode_request ;;
esac

# =============================================================================
print_summary
exit "$EXIT_CODE"
